### ISSUE TITLE
Device shown 'On Latest Update' even if Latest/Newer updates are available

### ISSUE THREAD

**Issue by AmithaVPadiyar** [Azure/iot-hub-device-update#140] opened 2022-03-15 13:27 UTC
I have a device with a module and the device belongs to the default or system-assigned group created. I have imported an update as well. I could see the Best available updates for the group as shown in the image below
![image](https://user-images.githubusercontent.com/99024735/158379739-c345300a-f52a-4a62-9220-fcfb0c22b292.png)
But for the device it still shows, the device is 'on latest update' even if the latest version reported by the device is less than the update version available.
![image](https://user-images.githubusercontent.com/99024735/158379963-6375ccc1-78b3-48e4-9f20-f8809e219827.png)
I created an immediate deployment for the group , but still not able to see the 'AllDevices' and 'InProgress' count set to 1. I could see module twin getting updated with 'action' set to 3 in the service metadata under desired properties.
![image](https://user-images.githubusercontent.com/99024735/158380016-b6f16f04-8370-41c4-9c9e-bb6c763067b5.png)
What could be the possible reasons for this behavior in the latest release ?

**Comment by alancshi** [comment] 2022-03-15 17:29
Hi @AmithaVPadiyar , does it stay in this state persistently? There can be some latency in reporting back status (up to 5 minutes in some cases before the message gets sent, since these are batched).  If it's stuck in that state, can you please share the twin again for us to look at?

**Comment by AmithaVPadiyar** [comment] 2022-03-15 17:44
@alancshi Yeah, I have tried a couple of times today. The device still has 'On Latest Update' flag set to yes and when i queried the deployment status via this API [GET https://{endpoint}/deviceupdate/{instanceId}/management/groups/{groupId}/deployments/{deploymentId}/status?api-version=2021-06-01-preview](url), I got the below response:
{
    "deploymentState": "Active",
    "totalDevices": 0,
    "devicesInProgressCount": 0,
    "devicesCompletedFailedCount": 0,
    "devicesCompletedSucceededCount": 0,
    "devicesCanceledCount": 0
}
I expected to see totalDevices and devicesInProgressCount set to 1.
Attached the twin for your reference[TestDeviceTwin.txt](https://github.com/Azure/iot-hub-device-update/files/8255909/TestDeviceTwin.txt)

**Comment by xinanqiu** [comment] 2022-03-15 18:09
Hi @AmithaVPadiyar , per twin you shared, the device is offline.
Could you please connect your device to see whether the deployment status will return the expected values?

**Comment by AmithaVPadiyar** [comment] 2022-03-16 13:41
@xinanqiu I verified the behavior for the device having the module with connected state, and when i queried the deployment status , i still same response :
{
    "deploymentState": "Active",
    "totalDevices": 0,
    "devicesInProgressCount": 0,
    "devicesCompletedFailedCount": 0,
    "devicesCompletedSucceededCount": 0,
    "devicesCanceledCount": 0
}
Even though i have created a deployment for the group, the above counts are 0 and the 'Updates In Progress' is still 0 as shown in the image.
![image](https://user-images.githubusercontent.com/99024735/158599998-b80ed137-0c84-4b82-a1e8-2df5dff88c71.png)
and in group section, i could see current deployment as shown below.
![image](https://user-images.githubusercontent.com/99024735/158601059-e1050066-f206-491c-bcb3-c3788657b369.png)

For the device it shows, OnLatestUpdate as 'yes' and deployment status 'Not started'.
![image](https://user-images.githubusercontent.com/99024735/158600117-3d23ca65-cff0-4275-a710-972fb1740bdf.png)
I have attached twin for your reference again [TwinInConnectedState.txt](https://github.com/Azure/iot-hub-device-update/files/8262491/TwinInConnectedState.txt)

**Comment by xinanqiu** [comment] 2022-03-16 19:15
@AmithaVPadiyar, which agent did you use?

Per twin you shared, the service has sent down the expected message to the agent. But the agent did not report back correct properties.

                "agent": {
                    "deviceProperties": {
                        "manufacturer": "TestManufacturer",
                        "model": "TestModel",
                        "interfaceId": "dtmi:azure:iot:deviceUpdate;1",
                        "aduVer": "DU;agent/0.8.0-rc1-public-preview"
                    },
                    "compatPropertyNames": "manufacturer,model",
                    "state": 0
                }

**Comment by AmithaVPadiyar** [comment] 2022-03-17 12:37
@xinanqiu / @alancshi  My concern is for the device it shows 'OnLatestUpdate' as 'yes' and deployment status as 'not started' as shown in image above and under group details you can see that the 'Updates in Progress' is still 0 even after deployment is created. 
When I queried the deployment status using API, the response says 'TotalDevices' count as 0 but state as 'Active'. I believe this shouldn't be the expected behavior.
Device agent processing the action and signal the device and report state is yet to be done.

**Comment by xinanqiu** [comment] 2022-03-17 18:12
Thanks @AmithaVPadiyar , OnLatestUpdate is a bug. 

It is by design that TotalDevices is 0. The device is count only when it reports back in-progress state.
Ideally, the device should report back DeploymentInprogress as soon as it received the deployment and then processing further operations.

https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-plug-and-play#state

But we heard your feedback about this experience. We'll discuss it internally about how to improve it.

**Comment by AmithaVPadiyar** [comment] 2022-03-18 13:58
@xinanqiu sure!!. In the public preview version i.e. previous release, I believe that when deployment is created for the device the 'totalDevicesCount' increases to 1 and 'devicesInProgressCount' also increases to 1.
The behavior was as per the expectation and experience was better with the public preview release.

**Comment by eshashah-msft** [comment] 2022-10-27 02:55
Closing this issue. The 'On Latest update' bug has been fixed.

**Closed by eshashah-msft** 2022-10-27 02:55 UTC
Labels: bug
