### ISSUE TITLE
Replacement workflow not working

### ISSUE THREAD

**Issue by JoergZeidler** [Azure/iot-hub-device-update#511] opened 2023-07-27 06:47 UTC
@jw-msft: Regarding comment in PR https://github.com/Azure/iot-hub-device-update/pull/322#discussion_r1275247801  a LOG file from my replacement issue is attached.

## Current Behavior
iothub-device-update: release v1.0.2

In my update handling are 2 steps handler involved.
First is an custom handler it's called "swupdate_consent_handler". Second one is the "swupdate_handler v1".
In the "swupdate_consent_handler" download step, the current active update for my download file "simulator 5.0.0.0" will be cancelled, because another update will be started. The new update file is called "simulator 5.1.0.0". 
The running steps will be successfully cancelled, and the replacement workflow will be started. After the workflow_transfer_data handling, the swupdate_consent_handler will be called again, but it seems with old information. That means, he detect again a cancel operation and for example the installed_criteria is from download file  "simulator 5.0.0.0". 

## Logs
[Replacement_Workflow.log](https://github.com/Azure/iot-hub-device-update/files/12180106/Replacement_Workflow.log)

**Comment by jw-msft** [comment] 2023-07-27 22:56
Thanks for the logs, @JoergZeidler.  It looks like the updateMetadata sent down for the 2 deployments are identical.  Was that expected?

See father down below -- I see the final overall Apply Success for the 2nd replacement deployment succeeds with 700 (Apply Success), but the "step_0" and "step_1" steps are reporting 800 (Cancel Success), which would be the reporting state of previous, replaced deployment that got canceled.  I would expect it to be something like 700 (Apply Success) instead.

Was your issue that the deployment update metadata was the same, or is the issue of concern the reporting of 800 (Cancel Success) in the "step_0" and "step_1" steps (presumably from the 1st deployment)?

It seems like the latter issue is a bug where the 1st, replaced deployment's child step results is making it into the reporting of the 2nd, replacement deployment instead of using the results of the 2nd replaced deployment child steps.


# Replacement itself seems to be operating as expected

The first workflowId is `572b9f21-69a4-49df-bfe1-d55d656bc898` that gets canceled and replaced:
```
Jul 27 06:18:23 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:23.6346Z 1087[1087] [I] Replacement. workflow '572b9f21-69a4-49df-bfe1-d55d656bc898' is being replaced with workflow 'db88bd93-f31e-4494-8bc6-bb3341b4e9c4'. [ADUC_Workflow_HandlePropertyUpdate]
Jul 27 06:18:23 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:23.6346Z 1087[1087] [I] Deferred Replacement workflow id [db88bd93-f31e-4494-8bc6-bb3341b4e9c4] since current workflow id [572b9f21-69a4-49df-bfe1-d55d656bc898] was still in progress. [ADUC_Workflow_HandlePropertyUpdate]
Jul 27 06:18:23 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:23.6347Z 1087[1087] [D] cancellationType(2) => Replacement [ADUC_Workflow_HandleUpdateAction]
Jul 27 06:18:23 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:23.6347Z 1087[1087] [I] Canceling request for in-progress operation. desiredAction: ProcessDeployment, cancellationType: Replacement [ADUC_Workflow_HandleUpdateAction]
...
...
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8204Z 1087[1668] [I] Requesting cancel operation (workflow id '1', level 1, step 1). [Cancel]
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8204Z 1087[1668] [I] Action 'Download' complete. Result: -1 (succeeded), 0 (0x0) [ADUC_Workflow_WorkCompletionCallback]
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8204Z 1087[1668] [W] Handling cancel completion, cancellation type 'Replacement'. [ADUC_Workflow_WorkCompletionCallback]
```

The 2nd workflowId is `db88bd93-f31e-4494-8bc6-bb3341b4e9c4` that replaces the 1st one successfully and successfully processes it:

```
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8204Z 1087[1668] [I] Starting process of deployment for 'Replacement' [ADUC_Workflow_WorkCompletionCallback]
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8207Z 1087[1668] [I] Using sandbox /var/lib/adu/downloads/db88bd93-f31e-4494-8bc6-bb3341b4e9c4 [ADUC_Workflow_MethodCall_Download]
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8207Z 1087[1668] [I] Setting UpdateState to DownloadStarted [ADUC_Workflow_SetUpdateStateHelper]
...
...
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8344Z 1087[2059] [I] Action 'Install' complete. Result: 600 (succeeded), 0 (0x0) [ADUC_Workflow_WorkCompletionCallback]
...
...
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8347Z 1087[2060] [D] Queueing message (t:0, c:0x7c005c50, m:{"deviceUpdate":{"__t":"c","agent":{"lastInstallResult":{"stepResults":{"step_0":{"resultCode":800,"extendedResultCode":0,"resultDetails":null},"step_1":{"resultCode":800,"extendedResultCode":0,"resultDetails":"backup success"}},"resultCode":700,"extendedResultCode":0,"resultDetails":""},"state":0,"workflow":{"action":3,"id":"db88bd93-f31e-4494-8bc6-bb3341b4e9c4"},"installedUpdateId":"{\"provider\":\"customer\",\"name\":\"simulator\",\"version\":\"5.1.0.0\"}"}}}) [ADUC_D2C_Message_SendAsync]
```

## Formatted report of success state

```json
{
    "deviceUpdate": {
        "__t": "c",
        "agent": {
            "lastInstallResult": {
                "stepResults": {
                    "step_0": {
                        "resultCode": 800,
                        "extendedResultCode": 0,
                        "resultDetails": null
                    },
                    "step_1": {
                        "resultCode": 800,
                        "extendedResultCode": 0,
                        "resultDetails": "backup success"
                    }
                },
                "resultCode": 700,
                "extendedResultCode": 0,
                "resultDetails": ""
            },
            "state": 0,
            "workflow": {
                "action": 3,
                "id": "db88bd93-f31e-4494-8bc6-bb3341b4e9c4"
            },
            "installedUpdateId": "{\"provider\":\"customer\",\"name\":\"simulator\",\"version\":\"5.1.0.0\"}"
        }
    }
}
```

## Explanation of reported success of replacement deployment
- step_0 -> resultCode: 800
  - [ADUC_Result_Cancel_Success](https://github.com/Azure/iot-hub-device-update/blob/b71516d3e85f09db48c06980448e3a07d90d05e4/src/adu_types/inc/aduc/types/adu_core.h#L256) - This one seems to be stale from the previous, replaced deployment--I would have expected it to be probably 700 (ADUC_Result_Apply_Success).
- step_1 -> resultCode: 800
  - [ADUC_Result_Cancel_Success](https://github.com/Azure/iot-hub-device-update/blob/b71516d3e85f09db48c06980448e3a07d90d05e4/src/adu_types/inc/aduc/types/adu_core.h#L256) - This one seems to be stale from the previous, replaced deployment also.
- overall resultCode: 700
  - [ADUC_Result_Apply_Success](https://github.com/Azure/iot-hub-device-update/blob/b71516d3e85f09db48c06980448e3a07d90d05e4/src/adu_types/inc/aduc/types/adu_core.h#L248)
- state: 0
  - [ADUCITF_State_Idle = 0](https://github.com/Azure/iot-hub-device-update/blob/b71516d3e85f09db48c06980448e3a07d90d05e4/src/adu_types/inc/aduc/types/update_content.h#L277) - Idle is the correct state for a successful deployment of an update workflow.

The first workflow's download sandbox was properly cleaned up as well:
```
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8204Z 1087[1668] [I] Starting process of deployment for 'Replacement' [ADUC_Workflow_WorkCompletionCallback]
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8204Z 1087[1668] [D] Property '_workFolder' not NULL - returning cached workfolder '/var/lib/adu/downloads/572b9f21-69a4-49df-bfe1-d55d656bc898' [workflow_get_workfolder]
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8204Z 1087[1668] [I] Cleanup sandbox before replacement workflow [ADUC_Workflow_WorkCompletionCallback]
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8204Z 1087[1668] [I] Destroying sandbox /var/lib/adu/downloads/572b9f21-69a4-49df-bfe1-d55d656bc898. workflowId: 572b9f21-69a4-49df-bfe1-d55d656bc898 [SandboxDestroy]
```

and the new workflow was correctly using the new sandbox:
```
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8207Z 1087[1668] [I] Setting sandbox /var/lib/adu/downloads/db88bd93-f31e-4494-8bc6-bb3341b4e9c4 [SandboxCreate]
Jul 27 06:18:24 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:24.8207Z 1087[1668] [I] Using sandbox /var/lib/adu/downloads/db88bd93-f31e-4494-8bc6-bb3341b4e9c4 [ADUC_Workflow_MethodCall_Download]
```

# updateMetadata identical for the 2 deployments

However, I took the value of the updateMetadata property for 2 workflowIds,replaced backslash + dbl-quote with just dbl-quote( `s/\\"/"/g` ), and did pretty-print format of them side-by-side.  The replacement workflowId's updateMetadata seems to be exactly the same as the 1st workflowId that got replaced.

![image](https://github.com/Azure/iot-hub-device-update/assets/84477130/e5763ff9-258b-4dae-9642-5775306918ce)

These are the log lines I used to extract out the updateMetadata values for the 2 deployment workflowIds:

## First deployment 572b9f21-69a4-49df-bfe1-d55d656bc898

```
Jul 27 06:17:33 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:17:33.1447Z 1087[1087] [D] Update Action info string ({"workflow":{"action":3,"id":"572b9f21-69a4-49df-bfe1-d55d656bc898"},"updateManifest":"{\"manifestVersion\":\"5\",\"updateId\":{\"provider\":\"customer\",\"name\":\"simulator\",\"version\":\"5.0.0.0\"},\"compatibility\":[{\"manufacturer\":\"customer\",\"model\":\"omnect-simulator\"}],\"instructions\":{\"steps\":[{\"handler\":\"omnect\/swupdate_consent:1\",\"files\":[\"fef14319c1a9f3bdd\"],\"handlerProperties\":{\"installedCriteria\":\"consent 5.0.0.0\"}},{\"handler\":\"microsoft\/swupdate:1\",\"files\":[\"fef14319c1a9f3bdd\"],\"handlerProperties\":{\"installedCriteria\":\"simulator 5.0.0.0\"}}]},\"files\":{\"fef14319c1a9f3bdd\":{\"fileName\":\"5.0.0.0\",\"sizeInBytes\":8,\"hashes\":{\"sha256\":\"iUtZj69sdEwj5mADsbGWKwDGCiNDmApykWbNCrfwNeM=\"}}},\"createdDateTime\":\"2022-12-19T09:54:58.2506376Z\"}","updateManifestSignature":null,"fileUrls":null}), property version (2) [OrchestratorUpdateCallback]
```

## Second, replacement deployment db88bd93-f31e-4494-8bc6-bb3341b4e9c4

```
Jul 27 06:18:23 8872498962a8 AducIotAgent[1087]: 2023-07-27T06:18:23.6341Z 1087[1087] [D] Update Action info string ({"workflow":{"action":3,"id":"db88bd93-f31e-4494-8bc6-bb3341b4e9c4"},"updateManifest":"{\"manifestVersion\":\"5\",\"updateId\":{\"provider\":\"customer\",\"name\":\"simulator\",\"version\":\"5.1.0.0\"},\"compatibility\":[{\"manufacturer\":\"customer\",\"model\":\"omnect-simulator\"}],\"instructions\":{\"steps\":[{\"handler\":\"omnect\/swupdate_consent:1\",\"files\":[\"fc6290b1a1b919557\"],\"handlerProperties\":{\"installedCriteria\":\"consent 5.1.0.0\"}},{\"handler\":\"microsoft\/swupdate:1\",\"files\":[\"fc6290b1a1b919557\"],\"handlerProperties\":{\"installedCriteria\":\"simulator 5.1.0.0\"}}]},\"files\":{\"fc6290b1a1b919557\":{\"fileName\":\"5.1.0.0\",\"sizeInBytes\":8,\"hashes\":{\"sha256\":\"ewtjXgT8lJJJ4hNX8Fa1h9WXaZ\/Yai8GxKA9NpTc4Pw=\"}}},\"createdDateTime\":\"2022-12-19T10:00:59.7756183Z\"}","updateManifestSignature":null,"fileUrls":null}), property version (3) [OrchestratorUpdateCallback]
```

**Comment by JoergZeidler** [comment] 2023-07-28 06:18
@jw-msft : Thanks for your deep analysis and explanation. 
It's really strange, but my two download manifests are different. Attached you find the manifests (it's just a demo). 

**My Expectation**

In the Download Step of my first step handler (swupdate_consent_handler), there is mechanism to check a user consent. The user consent is still not activated.  Here is code snipped of these part. 

```

ADUC_Result SWUpdateConsentHandlerImpl::Download(const tagADUC_WorkflowData* workflowData)
{
    ADUC_WorkflowHandle workflowHandle = workflowData->WorkflowHandle;
    Log_Info("swupdate waiting for user consent!!!!");
    Log_Info("swupdate consent Download starting (workflow: %s)",workflow_peek_id(workflowData->WorkflowHandle));
    while (false == consent)
    {
        // check if cancel request received
        if (workflow_is_cancel_requested(workflowHandle))
        {
            Log_Info("swupdate user consent Download cancel request");
            result = this->Cancel(workflowData);
            goto done;
        }

        // 1s timeout
        ThreadAPI_Sleep(1000);
    }

}
```
Update Process for the first Manifest "simulator 5.0.0.0" will be started via iothub portal:
![image](https://github.com/Azure/iot-hub-device-update/assets/62105035/90a4d956-9c3d-4a5c-a061-1fee52bfdbdd)

The steps handler will be called and waits for a user consent. In that case, i starting via iothub portal 
a new update with Manifest "simulator 5.1.0.0".
![image](https://github.com/Azure/iot-hub-device-update/assets/62105035/ce0ffaa6-8145-4c1d-8737-124c350958f6)


My expectation is that my download step will be recognize that the current download will be cancelled. This is exactly what happens and that is correct. But after the replacement workflow, the download step will be called again. And now is should still pending at the while loop, but that's not happen. 

The complete following sequence of install and apply should not happen in my scenario. 

I have double checked the content of the AducIotAgent module twin in the desired properties section. 

```
    "properties": {
        "desired": {
            "deviceUpdate": {
                    "updateManifest": xxxxx
```


Here it seems that's everything is as expected. First download, content for "simulator 5.0.0.0". After starting the download for "simulator 5.1.0.0" the content is switched as expected. 

But in the reported properties section,
```
    "properties": {
        "reported": {
            "deviceUpdate": {
                    "updateManifest": xxxxx
```
AducIotAgent still reports content for "simulator 5.0.0.0".



Imho, something is missing by the replacement workflow.....







[Manifests.zip](https://github.com/Azure/iot-hub-device-update/files/12190764/Manifests.zip)

**Comment by jw-msft** [comment] 2023-08-16 01:42
Rereading, it sounds like the question is why the `while (false == consent)` loop is skipped during processing of the replacement deployment after the first `this->Cancel()` call?

The only thing I can think of is that the Cancel() implementation (or something it is calling) is leading to `consent` being set to true and the scope of `consent` is living long enough to still have consent set to true when replacement deployment is processed (perhaps it needs to reset consent to false or the mechanism to set consent to true is occurring somehow between deployments?).

How is the `consent` variable set?  Also, is it a global variable, or static to the file?

Could you compile your custom extension using -g for debug symbols and:
- set a read/write watch on `consent` variable in gdb?
  - set breakpoint on the line with `while (false == consent)` with `break myfile.c:77` (replace myfile and line number 77)
  - run and break in there on first deployment, then run `awatch consent` to set read/write watch to break into whenever consent is read/written then `continue` 
  - If consent gets set to `true` after that before replacement deployment starts, then that would be why the while loop is being skipped the 2nd time around.
- set a conditional breakpoint on that line? i.e. `break myfile.c:77 if consent == 1`
- also, could set a breakpoint on every line that sets `consent`

Another option is:

Could you provide a zip of minimum repro (remove everything except what's important) extension project to allow trying it out in the debugger on our side?

**Comment by JoergZeidler** [comment] 2023-08-28 08:42
sorry for the late response, just back from vacation. 
I don't think the issue is regarding the consent implementation.

As you can see from my code snipped(https://github.com/Azure/iot-hub-device-update/issues/511#issuecomment-1655095572),  i added some Log Information in the download step. If you have a look in the provided log file(https://github.com/Azure/iot-hub-device-update/files/12180106/Replacement_Workflow.log) you will find the log message "swupdate user consent Download cancel request" 2 times. First time is clear because the first download will be cancelled. But the second time should not happened.

For me is the question why workflow_is_cancel_requested() return a true for the 2nd sequence.

**Comment by JoergZeidler** [comment] 2023-09-14 15:02
Hi @jw-msft : any news about this topic? 

Today I tried to narrow down the problem a little. To do this, I deliberately removed the custom handler(user_consent_handler) and only attempted to update with the standard swupdate_handler_v1 with small modifications.

1) swupdate_handler.cpp:
wrap via the is_cancel hanling a while loop
```
ADUC_Result SWUpdateHandlerImpl::Download(const tagADUC_WorkflowData* workflowData)
{
........
    while (true)
    {
        Log_Info("check!!!: workflow_is_cancel_requested");
        if (workflow_is_cancel_requested(workflowHandle))
        {
            result = this->Cancel(workflowData);
            Log_Info("done!!!: workflow_is_cancel_requested");

            goto done;
        }
        // 1s timeout
        ThreadAPI_Sleep(1000);
    }
....
}
```


2) swupdate_handler.cpp: add the need header file
`#include <azure_c_shared_utility/threadapi.h> // ThreadAPI_Sleep`

**Download process:**
Start the update process via IotHub-Update and just wait to see the log info "check!!!: workflow_is_cancel_requested" on device. Next start a new update deployment for the device.

My expectation is to see after cancellation of the first update the cyclic message "check!!!: workflow_is_cancel_requested" for the new update again, but that's not happen....

**Comment by jw-msft** [comment] 2023-10-27 17:37
Was heads down and looking again at this. Thanks for providing more info. We're tracking this internally and will investigate further.

**Comment by jw-msft** [comment] 2023-12-11 15:58
Closing as the internal tracking item has clear instructions to update this github issue.

**Closed by jw-msft** 2023-12-11 15:58 UTC
Labels: extensibility investigation

**Comment by JanZachmann** [comment] 2026-07-20 10:53
**Still present in 1.4.0 — root cause and a fix**

We hit this again on agent 1.4.0. Same setup: a two-step update where step 0 is a custom consent handler that waits in its `Download()`, step 1 is `microsoft/swupdate:2`. Deploy version A, and while A waits, deploy version B (replacement). B runs with A's `installedCriteria` and A's leftover cancel request, so B fails instead of installing.

Root cause (confirmed by log + code):

- On a replacement, `workflow_update_for_replacement` → `workflow_transfer_data` swaps the new manifest (`UpdateActionObject`/`UpdateManifestObject`/`PropertiesObject`) into the current workflow handle, but does **not** touch the handle's existing step `Children`.
- `PrepareStepsWorkflowDataObject` only rebuilds children when `childWorkflowCount != stepCount`. A and B both have 2 steps, so `2 == 2` → the rebuild is skipped and the old (A) children are reused.
- Result: the replacement's steps carry A's `installedCriteria` and A's `cancel_requested` flag. In our case the consent step reads A's version and immediately re-cancels → `Failed`.

Log evidence — the replacement download reuses the same workflow handle address as the replaced one (`h_addr:0x…` identical), and the consent step logs A's version for B's workflow id.

Fix that worked for us: free the target handle's children in `workflow_transfer_data` before/after swapping the manifest objects, so `PrepareStepsWorkflowDataObject` rebuilds them from the new manifest. That clears both the stale `installedCriteria` and the stale cancel flag. Happy to send a PR.
